
package com.keytalk.nextgen5.core.security;

/*
 * Class  :  ResponseType
 * Description : Support class
 *
 * Created by : KeyTalk IT Security BV on 2017
 * All rights reserved @ keytalk.com
 */

public enum ResponseType {
    RESPONSE_SUCCESS,
    RESPONSE_FAILURE,
    SC_SERVICE_UNAVAILABLE,
    AUTH_RESPONCE_ERROR,
    AUTH_RESPONCE_LOCKED_CREDENTIALS,
    AUTH_RESPONCE_RELOAD_PAGE,
    AUTH_RESPONCE_REQUIRE_CREDENTIALS,
    AUTH_RESPONCE_REQUIRE_RESET_CREDENTIALS_OPTION,
    AUTH_RESPONCE_REQUIRE_RESET_CREDENTIALS,
    AUTH_RESPONCE_REQUIRE_RESET_CREDENTIALS_DELAY,
    AUTH_REQUEST_DATA_NOT_AVAILABLE,
    AUTH_REQUEST_PUBLIC_KEY_NOT_AVAILABLE,
    AUTH_REQUEST_DELAY,
    AUTH_REQUEST_CHALLENGE;
}
